---
title: "Week 3 Discussion File"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## Part A: Make edits (no conflict)

```{r partner_1a}
# Partner 1: 
# Run the code below to see the original graph
# Change the code below to make the point color change based on 'cut', and update the theme to theme_bw(). Update the title to include your first name. 

ggplot(data = diamonds, aes(x = carat, y = price)) +
  geom_point(aes(color = "cut")) +
  theme_bw() +
  labs(title = "Sydney was here")
```

```{r partner_2a}
# Partner 2: 
# Run the code below to see the original graph
# Change the code below to make the geom a geom_jitter, and update the theme to theme_light. Update the title to include your first name. 

ggplot(data = diamonds, aes(x = color, y = carat)) +
  geom_jitter() +
  theme_light() +
  labs(title = "Lucas was here")
```

## PART B: Make problems

```{r break-it-1}
ggplot(data = diamonds, aes(x = depth, y = carat, color = cut)) +
  geom_violin() +
  theme_minimal()
  
# Here are my updates!
ideal_diamonds <- diamonds %>% 
  filter(cut == "Ideal")

ggplot(data = ideal_diamonds, aes(x = depth, y = carat)) +
  geom_jitter() +
  theme_minimal()
```

```{r break-it-2}
ideal_diamonds %>% 
  filter(color == "I")
```

## END Discussion 3
